language: java

install: mvn install -DskipTests=true ;

jdk:
  - oraclejdk8

deploy:
   edge: true
   provider: cloudfoundry
   username: gsarathkumar92@yahoo.in
   password: SMILE7day@
   api: https://api.run.pivotal.io
   organization: StudentManagement
   space: lovelybells
